# Java 17 kullanarak bir temel imaj seçin
FROM openjdk:17-jdk-slim

# Uygulama jar dosyasının oluşturulacağı dizin
VOLUME /tmp

# Jar dosyasını uygulama dizinine kopyalayın
COPY target/library-system.jar app.jar

# Uygulamanın çalıştırılacağı komut
ENTRYPOINT ["java","-jar","/app.jar"]
